### ISSUE TITLE
error LNK2019 IN DepthCapture.cpp

### ISSUE THREAD

**Issue by TamirCohen** [3dtof/voxelsdk#164]
I am Working on Vs2013 on 64bit, windows 10, voxelsdk version 0.6.10, QT 5.4.2, PCL 1.7.2:
While trying to build the sample project DepthCapture.cpp it throwed 2 errors 

The Code:
`#include "CameraSystem.h"
using namespace Voxel;

int main()
{
	CameraSystem sys;
}`

The errors:
1)
 Error	116	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall Voxel::CameraSystem::~CameraSystem(void)" (__imp_??1CameraSystem@Voxel@@UAE@XZ) referenced in function _main
2)
Error	115	error LNK2019: unresolved external symbol "__declspec(dllimport) public: __thiscall Voxel::CameraSystem::CameraSystem(void)" (__imp_??0CameraSystem@Voxel@@QAE@XZ) referenced in function _main

I followed the instructions of the installation on windows,
Every suggestion would be welcome.

also what enviorment did you use in order to install and use the SDK (for example in which operating system)
Thanks in advance

**Comment by TamirCohen** [comment]
Worked on ubuntu 14.04
